export const groupTitleOptions = [
    { value: "MD", label: "MD-Sales" },
    { value: "RO", label: "RO-Sales" },
    { value: "Filiale", label: "Filiale" },
    { value: "Francize", label: "Francize" },
    { value: "Marketing", label: "Marketing" },
    { value: "IndividualGroups", label: "Individual groups" },
    { value: "BusinessGroups", label: "Business groups" },
    { value: "Agency", label: "Agency" },
    { value: "GreenCard", label: "Green Card" },
    { value: "SalesUA", label: "SALES UA" },
    { value: "FranchiseOrhei", label: "Orhei Franchise" },
    { value: "FranchiseCantemir", label: "Cantemir Franchise" },
    { value: "FranchiseEdinet", label: "Edinet Franchise" },
    { value: "FranchiseDrochia", label: "Drochia Franchise" },
    { value: "FranchiseIaloveni", label: "Ialoveni Franchise" },
    { value: "FranchiseChisinauBuiucani", label: "Chisinau, Buiucani Franchise" },
    { value: "FranchiseCauseni", label: "Causeni Franchise" },
    { value: "FranchiseSoldanesti", label: "Soldanesti Franchise" },
    { value: "FranchiseRezina", label: "Rezina Franchise" },
    { value: "FranchiseChisinauRiscani", label: "Chisinau, Riscani Franchise" },
    { value: "FranchiseTimisoara", label: "Timisoara Franchise" },
    { value: "FranchiseNisporeni", label: "Nisporeni Franchise" },
    { value: "FranchiseCluj", label: "Cluj Franchise" },
    { value: "FranchiseStauceni", label: "Stauceni Franchise" },
    { value: "FranchiseHincesti", label: "Hincesti Franchise" },
    { value: "FranchiseCimislia", label: "Cimislia Franchise" },
];
