export const groupTitleOptions = [
    { value: "MD", label: "MD-Sales" },
    { value: "RO", label: "RO-Sales" },
    { value: "Filiale", label: "Filiale" },
    { value: "Francize", label: "Francize" },
    { value: "Marketing", label: "Marketing" },
    { value: "IndividualGroups", label: "Individual groups" },
    { value: "BusinessGroups", label: "Business groups" },
    { value: "Agency", label: "Agency" },
    { value: "GreenCard", label: "Green Card" },
    { value: "SalesUA", label: "SALES UA" },
    { value: "ORHEI", label: "Orhei Franchise" },
    { value: "CANTEMIR", label: "Cantemir Franchise" },
    { value: "EDINET", label: "Edinet Franchise" },
    { value: "DROCHIA", label: "Drochia Franchise" },
    { value: "IALOVENI", label: "Ialoveni Franchise" },
    { value: "BUIUCANI", label: "Chisinau, Buiucani Franchise" },
    { value: "CAUSENI", label: "Causeni Franchise" },
    { value: "SOLDANESTI", label: "Soldanesti Franchise" },
    { value: "REZINA", label: "Rezina Franchise" },
    { value: "RASCANI", label: "Chisinau, Riscani Franchise" },
    { value: "FranchiseTimisoara", label: "Timisoara Franchise" },
    { value: "NISPORENI", label: "Nisporeni Franchise" },
    { value: "FranchiseCluj", label: "Cluj Franchise" },
    { value: "STAUCENI", label: "Stauceni Franchise" },
    { value: "HANCESTI", label: "Hincesti Franchise" },
    { value: "CIMISLIA", label: "Cimislia Franchise" },
    {value: "HR", label: "HR"}
];
