name: Deploy to Cloud Run

on:
  push:
    branches:
      - Restyle4

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker
        run: |
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/pandaturcrm .
          docker push gcr.io/$PROJECT_ID/pandaturcrm

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy pandaturcrm \
            --image gcr.io/$PROJECT_ID/pandaturcrm \
            --region europe-north1 \
            --platform managed \
            --allow-unauthenticated
